export type PredefinedClauseType = {
  name: string;
  content: string; // SFDT JSON string
};

export const predefinedClauses: PredefinedClauseType[] = [
  {
    name: 'Revocation',
    content: JSON.stringify({
      optimizeSfdt: true,
      sec: [
        {
          secpr: {
            pw: 612,
            ph: 792,
            lm: 72,
            rm: 72,
            tm: 72,
            bm: 72,
            hd: 36,
            fd: 36,
            dfp: 0,
            doep: 0,
            bi: 0,
            enf: 2,
            fnf: 0,
            rif: 0,
            rie: 0,
            ifn: 1,
            ien: 1,
            pgns: 'Arabic',
            ncols: 1,
            eqw: 1,
            lbtc: 0,
            cols: [],
          },
          b: [
            {
              cf: { u: 1 },
              i: [
                {
                  cf: { u: 1 },
                  tlp: 'REVOCATION',
                },
              ],
            },
            {
              pf: {
                bdrs: {
                  tp: {},
                  lt: {},
                  rg: {},
                  bt: {},
                  h: {},
                  v: {},
                },
                stn: 'Normal',
                lif: {},
              },
              cf: {
                u: 0,
              },
              i: [],
            },
            {
              pf: {
                bdrs: {
                  tp: {},
                  lt: {},
                  rg: {},
                  bt: {},
                  h: {},
                  v: {},
                },
                stn: 'Normal',
                lif: {
                  lid: 0,
                  lilno: 0,
                  nsid: 26288459,
                },
              },
              cf: {
                u: 0,
              },
              i: [
                {
                  cf: {
                    u: 0,
                    bi: false,
                  },
                  tlp: 'I hereby revoke all previous Wills and condicils made by me.',
                },
              ],
            },
          ],
          hf: {},
        },
      ],
      cf: {
        b: false,
        i: false,
        fsz: 11,
        ff: 'Calibri',
        u: 0,
        st: 0,
        ba: 0,
        hc: 0,
        fszbi: 11,
        ffbi: 'Calibri',
        ac: false,
        ffa: 'Calibri',
        ffnfe: 'Calibri',
      },
      pf: {
        bdrs: {
          tp: {},
          lt: {},
          rg: {},
          bt: {},
          h: {},
          v: {},
        },
        lin: 0,
        rin: 0,
        fin: 0,
        ta: 0,
        bs: 0,
        as: 0,
        ls: 1,
        lst: 0,
        ol: 0,
        bi: false,
        klt: false,
        kwn: false,
        wc: true,
        lif: {},
      },
      li: [
        {
          alid: 0,
          lo: [],
          lid: 0,
          nsid: 26288459,
        },
      ],
      fst: {},
      tfl: {},
      dtw: 36,
      tc: 0,
      enf: 0,
      hv: '',
      sv: '',
      fmt: 0,
      pt: 0,
      dhtml: 0,
      ffs: 1,
      comp: 0,
      stytbl: 0,
      bg: {
        c: '#FFFFFF',
      },
      al: [
        {
          alid: 0,
          nsid: 26288459,
          lvl: [
            {
              cf: {},
              pf: {
                bdrs: {
                  tp: {},
                  lt: {},
                  rg: {},
                  bt: {},
                  h: {},
                  v: {},
                },
                lin: 36,
                fin: -18,
                lif: {},
              },
              isLgl: 0,
              fchar: 1,
              lilp: 1,
              nf: '%1.',
              psty: '',
              rl: 0,
              sa: 1,
            },
          ],
        },
      ],
      cm: [],
      r: [],
      cx: [],
      imgs: {},
    }),
  },
  {
    name: 'Appointment of Executors and Trustees',
    content: JSON.stringify({
      optimizeSfdt: true,
      sec: [
        {
          secpr: {
            pw: 612,
            ph: 792,
            lm: 72,
            rm: 72,
            tm: 72,
            bm: 72,
            hd: 36,
            fd: 36,
            dfp: 0,
            doep: 0,
            bi: 0,
            enf: 2,
            fnf: 0,
            rif: 0,
            rie: 0,
            ifn: 1,
            ien: 1,
            pgns: 'Arabic',
            ncols: 1,
            eqw: 1,
            lbtc: 0,
            cols: [],
          },
          b: [
            {
              cf: { u: 1 },
              i: [
                {
                  cf: { u: 1 },
                  tlp: 'APPOINTMENT OF EXECUTORS AND TRUSTEES',
                },
              ],
            },
            {
              pf: {
                bdrs: {
                  tp: {},
                  lt: {},
                  rg: {},
                  bt: {},
                  h: {},
                  v: {},
                },
                ls: 1.0791666507720947,
                lst: 0,
                stn: 'Normal',
                lif: {},
              },
              cf: {},
              i: [],
            },
            {
              pf: {
                bdrs: {
                  tp: {},
                  lt: {},
                  rg: {},
                  bt: {},
                  h: {},
                  v: {},
                },
                ls: 1.0791666507720947,
                lst: 0,
                stn: 'Normal',
                lif: {
                  lid: 1,
                  lilno: 0,
                  nsid: 43466311,
                },
              },
              cf: {
                u: 0,
                bi: false,
              },
              i: [
                {
                  cf: {
                    u: 0,
                    bi: false,
                  },
                  tlp: 'I appoint my Child Executor 1 and my Daughter Wendy Richman, to be the Executors of my Will and Trustees of my estate.',
                },
              ],
            },
            {
              pf: {
                bdrs: {
                  tp: {},
                  lt: {},
                  rg: {},
                  bt: {},
                  h: {},
                  v: {},
                },
                ls: 1.0791666507720947,
                lst: 0,
                stn: 'Normal',
                lif: {
                  lid: 1,
                  lilno: 0,
                  nsid: 43466311,
                },
              },
              cf: {
                u: 0,
                bi: false,
              },
              i: [
                {
                  cf: {
                    u: 0,
                    bi: false,
                  },
                  tlp: 'Provided that if Executor 1 and Wendy Richman shall die before me, or is at any time unable or unwilling to act or continue to act as Executor of my Will and Trsutee of my estate before all trusts in my Will have been fully performed, then I appoint, to be the Executor of my Will and Trustee of my estate.',
                },
                {
                  cf: {
                    u: 0,
                    bi: false,
                  },
                  tlp: '\u000b',
                },
                {
                  cf: {
                    u: 0,
                    bi: false,
                  },
                  tlp: '\u000b',
                },
                {
                  cf: {
                    u: 0,
                    bi: false,
                  },
                  tlp: 'The expression "my Trustee" or "my Trustees" used throughout this my Will shall include, where the context permits, the Executor and Trustee and Executors and Trustees for the time being of this my Will wether original, additions or',
                },
              ],
            },
          ],
          hf: {},
        },
      ],
      pf: {
        bdrs: {
          tp: {},
          lt: {},
          rg: {},
          bt: {},
          h: {},
          v: {},
        },
        lin: 0,
        rin: 0,
        fin: 0,
        ta: 0,
        bs: 0,
        as: 0,
        ls: 1,
        lst: 0,
        ol: 0,
        bi: false,
        klt: false,
        kwn: false,
        wc: true,
        lif: {},
      },
      fst: {},
      tfl: {},
      dtw: 36,
      tc: 0,
      enf: 0,
      hv: '',
      sv: '',
      fmt: 0,
      pt: 0,
      dhtml: 0,
      ffs: 1,
      comp: 0,
      stytbl: 0,
      bg: {
        c: '#FFFFFF',
      },
      sty: [
        {
          n: 'Normal',
          t: 0,
          pf: {
            bdrs: {
              tp: {},
              lt: {},
              rg: {},
              bt: {},
              h: {},
              v: {},
            },
            lif: {},
          },
          cf: {},
          nx: 'Normal',
        },
        {
          n: 'Heading 1',
          t: 0,
          pf: {
            bdrs: {
              tp: {},
              lt: {},
              rg: {},
              bt: {},
              h: {},
              v: {},
            },
            lin: 0,
            rin: 0,
            fin: 0,
            ta: 0,
            bs: 12,
            as: 0,
            ls: 1.0791666507720947,
            lst: 0,
            ol: 1,
            lif: {},
          },
          cf: {
            fsz: 16,
            ff: 'Calibri Light',
            fc: '#2F5496',
            ffa: 'Calibri Light',
            ffnfe: 'Calibri Light',
          },
          b: 'Normal',
          l: 'Heading 1 Char',
          nx: 'Normal',
        },
        {
          n: 'Heading 1 Char',
          t: 1,
          cf: {
            fsz: 16,
            ff: 'Calibri Light',
            fc: '#2F5496',
            ffa: 'Calibri Light',
            ffnfe: 'Calibri Light',
          },
          b: 'Default Paragraph Font',
        },
        {
          n: 'Default Paragraph Font',
          t: 1,
          cf: {},
        },
        {
          n: 'Heading 2',
          t: 0,
          pf: {
            bdrs: {
              tp: {},
              lt: {},
              rg: {},
              bt: {},
              h: {},
              v: {},
            },
            lin: 0,
            rin: 0,
            fin: 0,
            ta: 0,
            bs: 2,
            as: 0,
            ls: 1.0791666507720947,
            lst: 0,
            ol: 2,
            lif: {},
          },
          cf: {
            fsz: 13,
            ff: 'Calibri Light',
            fc: '#2F5496',
            ffa: 'Calibri Light',
            ffnfe: 'Calibri Light',
          },
          b: 'Normal',
          l: 'Heading 2 Char',
          nx: 'Normal',
        },
        {
          n: 'Heading 2 Char',
          t: 1,
          cf: {
            fsz: 13,
            ff: 'Calibri Light',
            fc: '#2F5496',
            ffa: 'Calibri Light',
            ffnfe: 'Calibri Light',
          },
          b: 'Default Paragraph Font',
        },
        {
          n: 'Heading 3',
          t: 0,
          pf: {
            bdrs: {
              tp: {},
              lt: {},
              rg: {},
              bt: {},
              h: {},
              v: {},
            },
            lin: 0,
            rin: 0,
            fin: 0,
            ta: 0,
            bs: 2,
            as: 0,
            ls: 1.0791666507720947,
            lst: 0,
            ol: 3,
            lif: {},
          },
          cf: {
            fsz: 12,
            ff: 'Calibri Light',
            fc: '#1F3763',
            ffa: 'Calibri Light',
            ffnfe: 'Calibri Light',
          },
          b: 'Normal',
          l: 'Heading 3 Char',
          nx: 'Normal',
        },
        {
          n: 'Heading 3 Char',
          t: 1,
          cf: {
            fsz: 12,
            ff: 'Calibri Light',
            fc: '#1F3763',
            ffa: 'Calibri Light',
            ffnfe: 'Calibri Light',
          },
          b: 'Default Paragraph Font',
        },
        {
          n: 'Heading 4',
          t: 0,
          pf: {
            bdrs: {
              tp: {},
              lt: {},
              rg: {},
              bt: {},
              h: {},
              v: {},
            },
            lin: 0,
            rin: 0,
            fin: 0,
            ta: 0,
            bs: 2,
            as: 0,
            ls: 1.0791666507720947,
            lst: 0,
            ol: 4,
            lif: {},
          },
          cf: {
            i: true,
            ff: 'Calibri Light',
            fc: '#2F5496',
            ffa: 'Calibri Light',
            ffnfe: 'Calibri Light',
          },
          b: 'Normal',
          l: 'Heading 4 Char',
          nx: 'Normal',
        },
        {
          n: 'Heading 4 Char',
          t: 1,
          cf: {
            i: true,
            ff: 'Calibri Light',
            fc: '#2F5496',
            ffa: 'Calibri Light',
            ffnfe: 'Calibri Light',
          },
          b: 'Default Paragraph Font',
        },
        {
          n: 'Heading 5',
          t: 0,
          pf: {
            bdrs: {
              tp: {},
              lt: {},
              rg: {},
              bt: {},
              h: {},
              v: {},
            },
            lin: 0,
            rin: 0,
            fin: 0,
            ta: 0,
            bs: 2,
            as: 0,
            ls: 1.0791666507720947,
            lst: 0,
            ol: 5,
            lif: {},
          },
          cf: {
            ff: 'Calibri Light',
            fc: '#2F5496',
            ffa: 'Calibri Light',
            ffnfe: 'Calibri Light',
          },
          b: 'Normal',
          l: 'Heading 5 Char',
          nx: 'Normal',
        },
        {
          n: 'Heading 5 Char',
          t: 1,
          cf: {
            ff: 'Calibri Light',
            fc: '#2F5496',
            ffa: 'Calibri Light',
            ffnfe: 'Calibri Light',
          },
          b: 'Default Paragraph Font',
        },
        {
          n: 'Heading 6',
          t: 0,
          pf: {
            bdrs: {
              tp: {},
              lt: {},
              rg: {},
              bt: {},
              h: {},
              v: {},
            },
            lin: 0,
            rin: 0,
            fin: 0,
            ta: 0,
            bs: 2,
            as: 0,
            ls: 1.0791666507720947,
            lst: 0,
            ol: 6,
            lif: {},
          },
          cf: {
            ff: 'Calibri Light',
            fc: '#1F3763',
            ffa: 'Calibri Light',
            ffnfe: 'Calibri Light',
          },
          b: 'Normal',
          l: 'Heading 6 Char',
          nx: 'Normal',
        },
        {
          n: 'Heading 6 Char',
          t: 1,
          cf: {
            ff: 'Calibri Light',
            fc: '#1F3763',
            ffa: 'Calibri Light',
            ffnfe: 'Calibri Light',
          },
          b: 'Default Paragraph Font',
        },
        {
          n: 'Heading 7',
          t: 0,
          pf: {
            bdrs: {
              tp: {},
              lt: {},
              rg: {},
              bt: {},
              h: {},
              v: {},
            },
            lin: 0,
            rin: 0,
            fin: 0,
            ta: 0,
            bs: 2,
            as: 0,
            ls: 1.0791666507720947,
            lst: 0,
            ol: 7,
            lif: {},
          },
          cf: {
            i: true,
            ff: 'Calibri Light',
            fc: '#1F3763',
            ffa: 'Calibri Light',
            ffnfe: 'Calibri Light',
          },
          b: 'Normal',
          l: 'Heading 7 Char',
          nx: 'Normal',
        },
        {
          n: 'Heading 7 Char',
          t: 1,
          cf: {
            i: true,
            ff: 'Calibri Light',
            fc: '#1F3763',
            ffa: 'Calibri Light',
            ffnfe: 'Calibri Light',
          },
          b: 'Default Paragraph Font',
        },
        {
          n: 'Heading 8',
          t: 0,
          pf: {
            bdrs: {
              tp: {},
              lt: {},
              rg: {},
              bt: {},
              h: {},
              v: {},
            },
            lin: 0,
            rin: 0,
            fin: 0,
            ta: 0,
            bs: 2,
            as: 0,
            ls: 1.0791666507720947,
            lst: 0,
            ol: 8,
            lif: {},
          },
          cf: {
            fsz: 10.5,
            ff: 'Calibri Light',
            fc: '#333333',
            ffa: 'Calibri Light',
            ffnfe: 'Calibri Light',
          },
          b: 'Normal',
          l: 'Heading 8 Char',
          nx: 'Normal',
        },
        {
          n: 'Heading 8 Char',
          t: 1,
          cf: {
            fsz: 10.5,
            ff: 'Calibri Light',
            fc: '#333333',
            ffa: 'Calibri Light',
            ffnfe: 'Calibri Light',
          },
          b: 'Default Paragraph Font',
        },
        {
          n: 'Heading 9',
          t: 0,
          pf: {
            bdrs: {
              tp: {},
              lt: {},
              rg: {},
              bt: {},
              h: {},
              v: {},
            },
            lin: 0,
            rin: 0,
            fin: 0,
            ta: 0,
            bs: 2,
            as: 0,
            ls: 1.0791666507720947,
            lst: 0,
            ol: 9,
            lif: {},
          },
          cf: {
            i: true,
            fsz: 10.5,
            ff: 'Calibri Light',
            fc: '#333333',
            ffa: 'Calibri Light',
            ffnfe: 'Calibri Light',
          },
          b: 'Normal',
          l: 'Heading 9 Char',
          nx: 'Normal',
        },
        {
          n: 'Heading 9 Char',
          t: 1,
          cf: {
            i: true,
            fsz: 10.5,
            ff: 'Calibri Light',
            fc: '#333333',
            ffa: 'Calibri Light',
            ffnfe: 'Calibri Light',
          },
          b: 'Default Paragraph Font',
        },
        {
          n: 'Header',
          t: 0,
          pf: {
            bdrs: {
              tp: {},
              lt: {},
              rg: {},
              bt: {},
              h: {},
              v: {},
            },
            as: 0,
            ls: 1,
            lst: 0,
            lif: {},
          },
          cf: {},
          b: 'Normal',
          nx: 'Header',
        },
        {
          n: 'Footer',
          t: 0,
          pf: {
            bdrs: {
              tp: {},
              lt: {},
              rg: {},
              bt: {},
              h: {},
              v: {},
            },
            as: 0,
            ls: 1,
            lst: 0,
            lif: {},
          },
          cf: {},
          b: 'Normal',
          nx: 'Footer',
        },
      ],
      li: [
        {
          alid: 1,
          lo: [],
          lid: 1,
          nsid: 43466311,
        },
      ],
      al: [
        {
          alid: 1,
          nsid: 43466311,
          lvl: [
            {
              cf: {},
              pf: {
                bdrs: {
                  tp: {},
                  lt: {},
                  rg: {},
                  bt: {},
                  h: {},
                  v: {},
                },
                lin: 36,
                fin: -18,
                lif: {},
              },
              isLgl: 0,
              fchar: 1,
              lilp: 1,
              nf: '%1.',
              psty: '',
              rl: 0,
              sa: 1,
            },
          ],
        },
      ],
      cm: [],
      r: [],
      cx: [],
      imgs: {},
    }),
  },
  {
    name: 'Payment of Debts and Expenses',
    content: JSON.stringify({
      optimizeSfdt: true,
      sec: [
        {
          secpr: {
            pw: 612,
            ph: 792,
            lm: 72,
            rm: 72,
            tm: 72,
            bm: 72,
            hd: 36,
            fd: 36,
            dfp: 0,
            doep: 0,
            bi: 0,
            enf: 2,
            fnf: 0,
            rif: 0,
            rie: 0,
            ifn: 1,
            ien: 1,
            pgns: 'Arabic',
            ncols: 1,
            eqw: 1,
            lbtc: 0,
            cols: [],
          },
          b: [
            {
              cf: { u: 1 },
              i: [
                {
                  cf: { u: 1 },
                  tlp: 'PAYMENT OF DEBTS AND EXPENSES',
                },
              ],
            },
            {
              pf: {
                bdrs: {
                  tp: {},
                  lt: {},
                  rg: {},
                  bt: {},
                  h: {},
                  v: {},
                },
                stn: 'Normal',
                lif: {},
              },
              cf: { u: 0 },
              i: [],
            },
            {
              pf: {
                bdrs: {
                  tp: {},
                  lt: {},
                  rg: {},
                  bt: {},
                  h: {},
                  v: {},
                },
                stn: 'Normal',
                lif: {
                  lid: 2,
                  lilno: 0,
                  nsid: 55500111,
                },
              },
              cf: { u: 0 },
              i: [
                {
                  cf: { u: 0 },
                  tlp: 'I direct my Executors to pay all my just debts as soon as practicable after my death.',
                },
              ],
            },
            {
              pf: {
                bdrs: {
                  tp: {},
                  lt: {},
                  rg: {},
                  bt: {},
                  h: {},
                  v: {},
                },
                stn: 'Normal',
                lif: {
                  lid: 2,
                  lilno: 0,
                  nsid: 55500111,
                },
              },
              cf: { u: 0 },
              i: [
                {
                  cf: { u: 0 },
                  tlp: 'All funeral and testamentary expenses shall be paid out of my estate.',
                },
              ],
            },
            {
              pf: {
                bdrs: {
                  tp: {},
                  lt: {},
                  rg: {},
                  bt: {},
                  h: {},
                  v: {},
                },
                stn: 'Normal',
                lif: {
                  lid: 2,
                  lilno: 0,
                  nsid: 55500111,
                },
              },
              cf: { u: 0 },
              i: [
                {
                  cf: { u: 0 },
                  tlp: 'My Executors shall also settle any taxes due in respect of my estate promptly and in full.',
                },
              ],
            },
          ],
          hf: {},
        },
      ],
      cf: {
        b: false,
        i: false,
        fsz: 11,
        ff: 'Calibri',
        u: 0,
        st: 0,
        ba: 0,
        hc: 0,
        fszbi: 11,
        ffbi: 'Calibri',
        ac: false,
        ffa: 'Calibri',
        ffnfe: 'Calibri',
      },
      pf: {
        bdrs: {
          tp: {},
          lt: {},
          rg: {},
          bt: {},
          h: {},
          v: {},
        },
        lin: 0,
        rin: 0,
        fin: 0,
        ta: 0,
        bs: 0,
        as: 0,
        ls: 1,
        lst: 0,
        ol: 0,
        bi: false,
        klt: false,
        kwn: false,
        wc: true,
        lif: {},
      },
      li: [
        {
          alid: 2,
          lo: [],
          lid: 2,
          nsid: 55500111,
        },
      ],
      al: [
        {
          alid: 2,
          nsid: 55500111,
          lvl: [
            {
              cf: {},
              pf: {
                bdrs: {
                  tp: {},
                  lt: {},
                  rg: {},
                  bt: {},
                  h: {},
                  v: {},
                },
                lin: 36,
                fin: -18,
                lif: {},
              },
              isLgl: 0,
              fchar: 1,
              lilp: 1,
              nf: '%1.',
              psty: '',
              rl: 0,
              sa: 1,
            },
          ],
        },
      ],
      cm: [],
      r: [],
      cx: [],
      imgs: {},
    }),
  },
  {
    name: 'Distribution of Personal Belongings',
    content: JSON.stringify({
      optimizeSfdt: true,
      sec: [
        {
          secpr: {
            pw: 612,
            ph: 792,
            lm: 72,
            rm: 72,
            tm: 72,
            bm: 72,
            hd: 36,
            fd: 36,
            dfp: 0,
            doep: 0,
            bi: 0,
            enf: 2,
            fnf: 0,
            rif: 0,
            rie: 0,
            ifn: 1,
            ien: 1,
            pgns: 'Arabic',
            ncols: 1,
            eqw: 1,
            lbtc: 0,
            cols: [],
          },
          b: [
            {
              cf: { u: 1 },
              i: [
                {
                  cf: { u: 1 },
                  tlp: 'DISTRIBUTION OF PERSONAL BELONGINGS',
                },
              ],
            },
            {
              pf: {
                bdrs: { tp: {}, lt: {}, rg: {}, bt: {}, h: {}, v: {} },
                stn: 'Normal',
                lif: {},
              },
              cf: { u: 0 },
              i: [],
            },
            {
              pf: {
                bdrs: { tp: {}, lt: {}, rg: {}, bt: {}, h: {}, v: {} },
                stn: 'Normal',
                lif: { lid: 3, lilno: 0, nsid: 55500222 },
              },
              cf: { u: 0 },
              i: [
                {
                  cf: { u: 0 },
                  tlp: 'I give my personal effects and household items to be shared among my children in equal shares.',
                },
              ],
            },
            {
              pf: {
                bdrs: { tp: {}, lt: {}, rg: {}, bt: {}, h: {}, v: {} },
                stn: 'Normal',
                lif: { lid: 3, lilno: 0, nsid: 55500222 },
              },
              cf: { u: 0 },
              i: [
                {
                  cf: { u: 0 },
                  tlp: 'If any item cannot be divided, I leave it to the discretion of my Executors to allocate fairly.',
                },
              ],
            },
            {
              pf: {
                bdrs: { tp: {}, lt: {}, rg: {}, bt: {}, h: {}, v: {} },
                stn: 'Normal',
                lif: { lid: 3, lilno: 0, nsid: 55500222 },
              },
              cf: { u: 0 },
              i: [
                {
                  cf: { u: 0 },
                  tlp: 'Any item not specifically mentioned in this Will shall form part of the residuary estate.',
                },
              ],
            },
          ],
          hf: {},
        },
      ],
      cf: {
        b: false,
        i: false,
        fsz: 11,
        ff: 'Calibri',
        u: 0,
        st: 0,
        ba: 0,
        hc: 0,
        fszbi: 11,
        ffbi: 'Calibri',
        ac: false,
        ffa: 'Calibri',
        ffnfe: 'Calibri',
      },
      pf: {
        bdrs: { tp: {}, lt: {}, rg: {}, bt: {}, h: {}, v: {} },
        lin: 0,
        rin: 0,
        fin: 0,
        ta: 0,
        bs: 0,
        as: 0,
        ls: 1,
        lst: 0,
        ol: 0,
        bi: false,
        klt: false,
        kwn: false,
        wc: true,
        lif: {},
      },
      li: [{ alid: 3, lo: [], lid: 3, nsid: 55500222 }],
      al: [
        {
          alid: 3,
          nsid: 55500222,
          lvl: [
            {
              cf: {},
              pf: {
                bdrs: { tp: {}, lt: {}, rg: {}, bt: {}, h: {}, v: {} },
                lin: 36,
                fin: -18,
                lif: {},
              },
              isLgl: 0,
              fchar: 1,
              lilp: 1,
              nf: '%1.',
              psty: '',
              rl: 0,
              sa: 1,
            },
          ],
        },
      ],
      cm: [],
      r: [],
      cx: [],
      imgs: {},
    }),
  },
  {
    name: 'Residuary Estate',
    content: JSON.stringify({
      optimizeSfdt: true,
      sec: [
        {
          secpr: {
            pw: 612,
            ph: 792,
            lm: 72,
            rm: 72,
            tm: 72,
            bm: 72,
            hd: 36,
            fd: 36,
            dfp: 0,
            doep: 0,
            bi: 0,
            enf: 2,
            fnf: 0,
            rif: 0,
            rie: 0,
            ifn: 1,
            ien: 1,
            pgns: 'Arabic',
            ncols: 1,
            eqw: 1,
            lbtc: 0,
            cols: [],
          },
          b: [
            {
              cf: { u: 1 },
              i: [
                {
                  cf: { u: 1 },
                  tlp: 'RESIDUARY ESTATE',
                },
              ],
            },
            {
              pf: {
                bdrs: { tp: {}, lt: {}, rg: {}, bt: {}, h: {}, v: {} },
                stn: 'Normal',
                lif: {},
              },
              cf: { u: 0 },
              i: [],
            },
            {
              pf: {
                bdrs: { tp: {}, lt: {}, rg: {}, bt: {}, h: {}, v: {} },
                stn: 'Normal',
                lif: { lid: 4, lilno: 0, nsid: 55500333 },
              },
              cf: { u: 0 },
              i: [
                {
                  cf: { u: 0 },
                  tlp: 'I give the residue of my estate to my spouse, if they survive me by 30 days.',
                },
              ],
            },
            {
              pf: {
                bdrs: { tp: {}, lt: {}, rg: {}, bt: {}, h: {}, v: {} },
                stn: 'Normal',
                lif: { lid: 4, lilno: 0, nsid: 55500333 },
              },
              cf: { u: 0 },
              i: [
                {
                  cf: { u: 0 },
                  tlp: 'If my spouse does not survive me, I give the residue to my children in equal shares.',
                },
              ],
            },
            {
              pf: {
                bdrs: { tp: {}, lt: {}, rg: {}, bt: {}, h: {}, v: {} },
                stn: 'Normal',
                lif: { lid: 4, lilno: 0, nsid: 55500333 },
              },
              cf: { u: 0 },
              i: [
                {
                  cf: { u: 0 },
                  tlp: 'If any child predeceases me, their share shall pass to their children in equal shares.',
                },
              ],
            },
          ],
          hf: {},
        },
      ],
      cf: {
        b: false,
        i: false,
        fsz: 11,
        ff: 'Calibri',
        u: 0,
        st: 0,
        ba: 0,
        hc: 0,
        fszbi: 11,
        ffbi: 'Calibri',
        ac: false,
        ffa: 'Calibri',
        ffnfe: 'Calibri',
      },
      pf: {
        bdrs: { tp: {}, lt: {}, rg: {}, bt: {}, h: {}, v: {} },
        lin: 0,
        rin: 0,
        fin: 0,
        ta: 0,
        bs: 0,
        as: 0,
        ls: 1,
        lst: 0,
        ol: 0,
        bi: false,
        klt: false,
        kwn: false,
        wc: true,
        lif: {},
      },
      li: [{ alid: 4, lo: [], lid: 4, nsid: 55500333 }],
      al: [
        {
          alid: 4,
          nsid: 55500333,
          lvl: [
            {
              cf: {},
              pf: {
                bdrs: { tp: {}, lt: {}, rg: {}, bt: {}, h: {}, v: {} },
                lin: 36,
                fin: -18,
                lif: {},
              },
              isLgl: 0,
              fchar: 1,
              lilp: 1,
              nf: '%1.',
              psty: '',
              rl: 0,
              sa: 1,
            },
          ],
        },
      ],
      cm: [],
      r: [],
      cx: [],
      imgs: {},
    }),
  },
];
